language: objective-c
osx_image: xcode9.1

script:
  - set -o pipefail
  - xcodebuild test
      -workspace PHAssetResourceInputStream.xcworkspace
      -scheme PHAssetResourceInputStream
      -sdk iphonesimulator
      -enableCodeCoverage YES
      -destination "name=iPhone 7"
      | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash)
