language: objective-c
# https://github.com/travis-ci/travis-ci/issues/7031
# Stick with the 8.1 version for now due to the duplicate simulators issue on iOS 10.2
osx_image: xcode8.1

script:
  - set -o pipefail
  - xcodebuild test
      -workspace PHAssetResourceInputStream.xcworkspace
      -scheme PHAssetResourceInputStream
      -sdk iphonesimulator
      -destination "name=iPhone 7"
      | xcpretty